In [1]:
# Import NumPy
import numpy as np

In [2]:
# Create a NumPy array
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a


array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [3]:
#1.# How many negative numbers are there?


# Get the negative numbers
negative_numbers = a[a < 0]

print(a[a < 0])
len(a[a < 0])


[-2 -1 -6 -7]


4

In [25]:
#2.How many positive numbers are there?

# Count the number of positive numbers
print(a[a > 0])

# Print the number of positive numbers
print(a[a > 0].size)




[ 4 10 12 23  3]
5


In [6]:
#3.How many even positive numbers are there?
# a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
# Select the positive numbers
# Select the even positive numbers
print(a[(a > 0) & (a % 2 == 0)])
print(a[(a > 0) & (a % 2 == 0)].shape)


[ 4 10 12]
(3,)


In [7]:
# 4.If you were to add 3 to each data point, how many positive numbers would there be?
# a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# Add 3 to each data point

# Select the positive numbers
add_three = a + 3
print(add_three[add_three > 0])
add_three[add_three > 0].size






[ 7 13 15 26  1  2  3  3  3  6]


10

In [4]:
# 5.If you squared each number, what would the new mean and standard deviation be?
(a**2).mean()


74.0

In [5]:
(a ** 2).std()


144.0243035046516

In [6]:
# 6.A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

avg = a.mean()
avg



3.0

In [7]:
a - avg


array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [8]:
(a - a.mean()).mean()


0.0

In [11]:
# 7.Calculate the z-score for each data point. Recall that the z-score is given by:
# Z=x−μ/σ

# Calculate the mean of the dataset
# Calculate the standard deviation of the dataset
# Calculate the z-score for each data point

zscores = (a - a.mean()) / a.std()
zscores



array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
# 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.